#!/bin/sh

machine="hd51"
hdd_mount="/media/usb"
mountpoint -q /media/hdd && hdd_mount="/media/hdd"
servicedir="$hdd_mount/service"
kernelname="kernel.bin"
picture_source="/usr/share/tuxbox/neutrino/icons"
rootfsname="neutrino-image-$machine.ext4"
devbase="/dev/mmcblk0p"
dev_display="/dev/dbox/oled0"
part_to_use="$1"
rootdevice="$(sed -e 's/^.*root=//' -e 's/ .*$//' < /proc/cmdline)"

if ! [[ $1 =~ ^[1-4]+$ ]]; then
        if echo "$rootdevice" | grep "3" >> /dev/null; then
                part_to_use="1"
        elif echo "$rootdevice" | grep "5" >> /dev/null; then
                part_to_use="2"
        elif echo "$rootdevice" | grep "7" >> /dev/null; then
                part_to_use="3"
        elif echo "$rootdevice" | grep "9" >> /dev/null; then
                part_to_use="4"
        fi
fi

exit_done() {
	sleep 3
        clear
	if [ $rootdevice = $devbase$root ]; then
		echo "...Reboot" > $dev_display && systemctl --force --force reboot
        else
            	systemctl start neutrino
        fi
        exit 0;
}


[  -z "$2" ] && [  -z "$1" ] && [ ! -d "$hdd_mount" ] && { printf '\n\033[31m%s\n' "Give the destination path an argument" && exit_done; }

if [[ "$part_to_use" =~ ^[0-9]+$ ]]; then
        if  [ "$part_to_use" -lt 1 ] || [ $1 -gt 4 ]; then
		{ printf '\n\033[31m%s\n' "Choose a valid partition [1-4]"; exit_done; }
        elif [ "$part_to_use" = 1 ]; then
                part=1; kernel=2; root=3
        elif [ "$part_to_use" = 2 ]; then
                part=2; kernel=4; root=5
        elif [ "$part_to_use" = 3 ]; then
                part=3; kernel=6; root=7
        elif [ "$part_to_use" = 4 ]; then
                part=4; kernel=8; root=9
	fi
fi

function stop_services () {
        pidof smbd >> /dev/null && systemctl stop smb
        pidof nmbd >> /dev/null && systemctl stop nmb
        pidof xupnpd >> /dev/null && systemctl stop xupnpd
        pidof udpxy >> /dev/null && systemctl stop udpxy
        netstat -tl | grep nfs >> /dev/null && systemctl stop nfs-server && systemctl stop nfs-mountd && systemctl stop nfs-statd
        pidof oscam >> /dev/null && systemctl stop oscam
        pidof cccam >> /dev/null && systemctl stop cccam
        pidof gbox >> /dev/null && systemctl stop gbox
        netstat -tl | grep webmin >> /dev/null && systemctl stop webmin
        netstat -tl | grep sunrpc >> /dev/null && systemctl -q stop rpcbind
        netstat -tl | grep ftp >> /dev/null && systemctl stop proftpd
        pidof minidlnad >> /dev/null && systemctl stop minidlna
        pidof automount >> /dev/null && systemctl stop autofs
        pidof ntpdate >> /dev/null && systemctl stop ntpdate
        cd /etc && git status  >> /dev/null && systemctl -q stop etckeeper
        pidof sshd >> /dev/null && systemctl stop sshd.socket
	sleep 5
}

pidof neutrino >> /dev/null && killall -9 neutrino
clear
convert -resize 1920x1080 -gravity center -extent 1920x1080 $picture_source/update.jpg bgra:/dev/fb0

[ ! -z "$2" ] && mountpoint -q "$2" && space_available="$(df -Pk $2 | awk 'NR==2 {print $4}')"
[ -z "$2"  ] && [ ! -z "$1" ] && mountpoint -q "$1" && ! [[ "$1" =~ ^[0-9]+$ ]] && space_available="$(df -Pk $1 | awk 'NR==2 {print $4}')"
[ -z "$2"  ] && mountpoint -q "$hdd_mount" && [[ "$1" =~ ^[0-9]+$ ]] && space_available="$(df -Pk $hdd_mount | awk 'NR==2 {print $4}')"
[ -z "$2"  ] && mountpoint -q "$hdd_mount" && [ -z "$1" ] && space_available="$(df -Pk $hdd_mount | awk 'NR==2 {print $4}')"
if [ ! -z "$space_available" ] && [ "$space_available" -lt 1048576 ]; then
	printf '\n\033[31m%s\n\t' "You need at least 1G of free space on your device"
	exit_done; 
fi

printf '\n\n\n\033[1m%s\n\033[0m' "Creating backup of partition $part" && echo "Creating backup of partition $part" > "$dev_display"
[ ! -z "$2" ] && destination="$2/backup/partition$part/$machine"
[ -z "$2"  ] && ! [[ "$1" =~ ^[0-9]+$ ]] && destination="$1/backup/partition$part/$machine"
[ -z "$2"  ] && [[ "$1" =~ ^[0-9]+$ ]] && destination="$servicedir/image/backup/partition$part/$machine"
[ -z "$2"  ] && [ -z "$1" ] && destination="$servicedir/image/backup/partition$part/$machine"

[ -d "$destination" ] && rm -rf "$destination"
mkdir -p "$destination"

[[ "$rootdevice" = "$devbase$root" ]] && stop_services
mountpoint -q /mnt/partition_"$part" && systemctl stop mnt-partition_"$part".mount

printf '\n\033[33m%s\033[37m%s\n' "Creating kernel backup in $destination/$kernelname " && echo "Creating kernel backup" > "$dev_display"
pv -w 100 < "$devbase$kernel" > "$destination/$kernelname"

printf '\n\033[33m%s\033[37m%s\n' "Creating rootfs backup in $destination/$rootfsname" && echo "Creating rootfs backup" > "$dev_display"
e2image -ra "$devbase$root" - | pv -w 100 -s800M | bzip2 --fast > "$destination/$rootfsname.bz2"

[ -f "$servicedir/image/imageversion_partition_$part" ] && cp -f "$servicedir/image/imageversion_partition_$part" "$destination/imageversion"
mountpoint -q /mnt/partition_"$part" || systemctl start mnt-partition_"$part".mount

printf '\n\033[1m\033[32m%s\033[0m\n' "Backup successfully completed"  && echo "Backup successfully completed" > "$dev_display"

exit_done;
